.TH "FOO" "1" "2022-2026" "0.1.0" "foo"
.SH NAME
.PP
foo
.SH SYNOPSIS
.PP
\f[B]foo\f[R] [\f[I]OPTIONS\f[R]...]
.SH DESCRIPTION
.PP
  ______   ______     ______
 /\\  ___\\ /\\  __ \\   /\\  __ \\
 \\ \\  __\\ \\ \\ \\/\\ \\  \\ \\ \\/\\ \\
  \\ \\_\\    \\ \\_____\\  \\ \\_____\\
   \\/_/     \\/_____/   \\/_____/
.SH OPTIONS
.SS optional:
.P
\f[B]-h\f[R],\ \f[B]--help\f[R]
.RS 4
show this help message and exit
.P
.RE
\f[B]-v\f[R],\ \f[B]--version\f[R]
.RS 4
show version information and exit
.P
.RE
\f[B]-d\f[R],\ \f[B]--dump\f[R]
.RS 4
dump default configuration and exit
.P
.RE
\f[B]-c\f[R] \f[I]CMD\f[R],\ \f[B]--console\f[R] \f[I]CMD\f[R]
.RS 4
run options in console mode and exit
.P
.RE
.RS 4
separate with quotes
.P
.RE
.SS sub-command:
.P
\f[B]app-algo\f[R]
.RS 4
apply algorithm
.P
.RE
\f[B]app-dp\f[R]
.RS 4
apply design pattern
.P
.RE
\f[B]app-ds\f[R]
.RS 4
apply data structure
.P
.RE
\f[B]app-num\f[R]
.RS 4
apply numeric
.P
.RE
.SH AUTHOR
.PP
ryftchen
.SH COPYRIGHT
.PP
Copyright (c) 2022-2026 ryftchen. All rights reserved.
