include_guard()

if(NOT COMMIT_REVISION STREQUAL "")
    add_compile_options(-D_COMMIT_REVISION="${COMMIT_REVISION}")
endif()
if(NOT TARGET_PROCESSOR STREQUAL "")
    add_compile_options(-D_TARGET_PROCESSOR="${TARGET_PROCESSOR}")
endif()
if(PRECOMPILED_HEADER)
    add_compile_options(-D_PRECOMPILED_HEADER)
endif()
if(RUNTIME_PRINTING)
    add_compile_options(-D_RUNTIME_PRINTING)
endif()
