include_guard()

find_program(GIT_EXECUTABLE git)
set(COMMIT_REVISION "" CACHE STRING "commit revision" FORCE)
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND git rev-parse --short=7 HEAD
        OUTPUT_VARIABLE GIT_REV_PARSE_SHORT_OUTPUT
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT GIT_REV_PARSE_SHORT_OUTPUT STREQUAL "")
        set(COMMIT_REVISION ${GIT_REV_PARSE_SHORT_OUTPUT} CACHE STRING "commit revision" FORCE)
    endif()
elseif()
    message(STATUS "Unknown version control")
endif()
if(NOT DEFINED TARGET_PROCESSOR)
    set(TARGET_PROCESSOR "" CACHE STRING "target processor" FORCE)
    execute_process(
        COMMAND ${CMAKE_CXX_COMPILER} -dumpmachine
        OUTPUT_VARIABLE COMPILER_DUMPMACHINE_OUTPUT
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT COMPILER_DUMPMACHINE_OUTPUT STREQUAL "")
        set(TARGET_PROCESSOR ${COMPILER_DUMPMACHINE_OUTPUT} CACHE STRING "target processor" FORCE)
    endif()
endif()

option(TOOLCHAIN_PCH "toolchain precompiled header" OFF)
option(TOOLCHAIN_UNITY "toolchain unity build" OFF)
option(TOOLCHAIN_CCACHE "toolchain ccache" OFF)
option(TOOLCHAIN_DISTCC "toolchain distcc" OFF)
set(PRECOMPILED_HEADER OFF)
if(TOOLCHAIN_PCH)
    message(STATUS "Using precompiled header")
    set(PRECOMPILED_HEADER ON)
endif()
if(TOOLCHAIN_UNITY)
    message(STATUS "Using unity build")
    set(CMAKE_UNITY_BUILD ON)
endif()
if(TOOLCHAIN_CCACHE)
    find_program(CCACHE_EXECUTABLE ccache)
    if(CCACHE_EXECUTABLE)
        message(STATUS "Using ccache")
        set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_EXECUTABLE})
        set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_EXECUTABLE})
    elseif()
        message(WARNING "No ccache program")
    endif()
endif()
if(TOOLCHAIN_DISTCC)
    find_program(DISTCC_EXECUTABLE distcc)
    if(DISTCC_EXECUTABLE)
        message(STATUS "Using distcc")
        if(NOT
           (TOOLCHAIN_CCACHE
            AND CCACHE_EXECUTABLE
            AND (DEFINED ENV{CCACHE_PREFIX})
            AND ("$ENV{CCACHE_PREFIX}" STREQUAL "distcc")))
            set(CMAKE_C_COMPILER_LAUNCHER ${DISTCC_EXECUTABLE})
            set(CMAKE_CXX_COMPILER_LAUNCHER ${DISTCC_EXECUTABLE})
        endif()
    elseif()
        message(WARNING "No distcc program")
    endif()
endif()
unset(TOOLCHAIN_PCH CACHE)
unset(TOOLCHAIN_UNITY CACHE)
unset(TOOLCHAIN_CCACHE CACHE)
unset(TOOLCHAIN_DISTCC CACHE)
