name: CI workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'CI for foo'
        default: ''
        required: false

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Prepare for environment
      run: |
        sudo apt-get install -y cmake llvm-11 clang-11 libclang-11-dev
        sudo apt-get install clang-format-11 clang-tidy-11
        sudo apt-get install python3 pylint black shellcheck
        wget https://github.com/mvdan/sh/releases/download/v3.4.2/shfmt_v3.4.2_linux_amd64 \
        && sudo mv shfmt_v3.4.2_linux_amd64 shfmt && sudo mv shfmt /usr/local/bin/ \
        && sudo chmod +x /usr/local/bin/shfmt
        sudo apt-get install valgrind
        git clone https://github.com/KDAB/codebrowser.git && cd codebrowser/ \
        && git reset --hard 73fce32fc696b3f6eb2a678397328d9ce1ad4cf6 \
        && cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ && make -j4 \
        && sudo make install && cd ..

    - name: Code format
      run: ./script/build.sh --format

    - name: Static code analysis
      run: ./script/build.sh --analysis

    - name: Build
      run: ./script/build.sh --release

    - name: Test
      run: |
        export TERM=linux
        export TERMINFO=/etc/terminfo
        ./script/test.py --valgrind

    - name: Generate html
      run: ./script/build.sh --html
