---
name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      name:
        description: 'CI'
        default: 'Manual trigger'
        required: false

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          export FOO_ENV=GITHUB_ACTION
          ./.github/workflows/install.sh

      - name: Check
        run: |
          ./script/build.sh --release --format --analysis
          git status

      - name: Build
        run: |
          ./script/build.sh --cleanup
          ./script/build.sh --release
          ./script/build.sh --release --html --backup --tag

      - name: Test
        run: |
          export TERM=linux
          export TERMINFO=/etc/terminfo
          ./script/test.py --build release --valgrind

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: foo_artifact
          path: ./temp/foo_html_*.tar.bz2
          retention-days: 7
...
