name: CI workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'CI for foo'
        default: ''
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Prepare for environment
      run: |
        sudo apt-get install -y cmake llvm-11 clang-11 libclang-11-dev
    - name: Build
      run: |
        cd ./foo
        ./script/build.sh
