name: CI

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get purge -y llvm-* clang-* libllvm-* libclang-*
        ./.github/workflows/CI.sh

    - name: Check code
      run: ./script/build.sh --release --format --analysis

    - name: Build
      run: | 
        ./script/build.sh --release
        ./script/build.sh --release --html

    - name: Test
      run: |
        export TERM=linux
        export TERMINFO=/etc/terminfo
        ./script/test.py --valgrind

    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: foo_artifact
        path: ./temp/foo_html_*.tar.bz2
        retention-days: 3