name: CI workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'CI for foo'
        default: ''
        required: false

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Prepare for environment
      run: |
        sudo apt-get install -y cmake llvm-11 clang-11 libclang-11-dev
        sudo apt-get install clang-format-11 clang-tidy-11
        sudo apt-get install python3 pylint black shellcheck
        sudo wget https://github.com/mvdan/sh/releases/download/v3.4.2/shfmt_v3.4.2_linux_amd64
        sudo mv shfmt_v3.4.2_linux_amd64 shfmt && sudo mv shfmt /usr/local/bin/
        sudo chmod +x /usr/local/bin/shfmt
        sudo apt-get install valgrind
        cmake --version
        clang++-11 --version
        clang-format-11 --version
        clang-tidy-11 --version
        python3 --version
        pylint --version
        black --version
        shellcheck --version
        shfmt --version
        valgrind --version

    - name: Code format
      run: ./script/build.sh --format

    - name: Static code analysis
      run: ./script/build.sh --analysis

    - name: Build
      run: ./script/build.sh --release

    - name: Test
      run: ./script/test.py --valgrind
