---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    permissions:
      contents: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/build.sh --hook --spell --format --lint --statistics
          ./script/build.sh --release --browser --doxygen

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: foo_artifact
          path: ./document/archive/foo_*.tar.bz2
          retention-days: 7

      - name: Initialize
        if: github.event_name == 'push'
        run: |
          git checkout gh-pages
          git reset --hard 088da5a87090f9886c01af5f2a57519f5ebf2428
          git push --force origin gh-pages
          git checkout master

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.event_name == 'workflow_dispatch'
        with:
          branch: gh-pages
          folder: ./document/doxygen
          commit-message: 'chore: deploy to gh-pages from @ ${{ github.repository }}@${{ github.sha }}'

  dynamic_analysis:
    name: Dynamic analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/run.py --check cov mem --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Test
        run: |
          ./script/run.py --test --build rls --repeat 1
          cat ./.cache/foo_run.report

      - name: Run
        run: |
          ./script/run.py --build rls --repeat 1
          cat ./.cache/foo_run.report

  extended_analysis:
    name: Extended analysis
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.22.2
        with:
          languages: cpp
          config-file: ./.github/actions/codeql/codeql-config.yml

      - name: Manual build
        run: |
          ./script/build.sh
          ./script/build.sh --test

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2.22.2
...
