---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  precheck:
    name: Precheck
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2.13.0
        with:
          files: |
            **/*.{cpp,hpp,tpp,py,sh}
          incremental_files_only: false
          config: ./.github/actions/cspell/cspell.json
          verbose: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Manual build
        run: |
          export CC=/usr/bin/clang-12 CXX=/usr/bin/clang++-12
          cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build
          cmake -S ./test -B ./test/build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build ./test/build

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  static_analysis:
    name: Static analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container: ryftchen/foo:latest

    permissions:
      contents: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/build.sh --format --lint --release
          git status

      - name: Archive
        run: |
          ./script/build.sh --browser --doxygen --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: foo_artifact
          path: ./temporary/foo_*.tar.bz2
          retention-days: 7

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.event_name == 'workflow_dispatch'
        with:
          branch: gh-pages
          folder: ./document/doxygen
          commit-message: 'chore: deploy to gh-pages from @ ${{ github.repository }}@${{ github.sha }}'

  dynamic_analysis:
    name: Dynamic analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container: ryftchen/foo:latest

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./script/build.sh --release

      - name: Test
        run: |
          ./script/run.py --test --build rls

      - name: Run
        run: |
          ./script/run.py --check cov mem --build rls
...
