---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  precheck:
    name: Precheck
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: ryftchen/foo:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling
        uses: check-spelling/check-spelling@v0.0.21
        with:
          config: ./.github/actions/check_spelling
          post_comment: 0
          shortest_word: 4
          extra_dictionaries:
            cspell:bash/bash-words.txt
            cspell:cpp/src/compiler-clang-attributes.txt
            cspell:cpp/src/compiler-gcc.txt
            cspell:cpp/src/cpp.txt
            cspell:cpp/src/ecosystem.txt
            cspell:cpp/src/lang-jargon.txt
            cspell:cpp/src/lang-keywords.txt
            cspell:cpp/src/stdlib-c.txt
            cspell:cpp/src/stdlib-cerrno.txt
            cspell:cpp/src/stdlib-cmath.txt
            cspell:cpp/src/stdlib-cpp.txt
            cspell:en_GB/src/aoo-mozilla-en-dict/en-GB.dic
            cspell:en_GB/src/hunspell/en_GB.dic
            cspell:en_GB/src/wordsEnGb.txt
            cspell:en_US/src/aoo-mozilla-en-dict/en_US.dic
            cspell:en_US/src/en_US.txt
            cspell:en_US/src/hunspell/en_US.dic
            cspell:filetypes/filetypes.txt
            cspell:python/src/python/python-lib.txt
            cspell:python/src/python/python.txt
            cspell:software-terms/src/software-terms.txt
            cspell:software-terms/src/software-tools.txt
          check_extra_dictionaries: ''

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Manual build
        run: |
          export CC=/usr/bin/clang-12 CXX=/usr/bin/clang++-12
          cmake -S . -B ./build -G Ninja -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build
          cmake -S ./test -B ./test/build -G Ninja -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_BUILD_TYPE=Release
          cmake --build ./test/build

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  static_analysis:
    name: Static analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container: ryftchen/foo:latest

    permissions:
      contents: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/build.sh --format --lint --release
          git status

      - name: Archive
        run: |
          ./script/build.sh --browser --doxygen --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: foo_artifact
          path: ./temporary/foo_*.tar.bz2
          retention-days: 7

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.event_name == 'workflow_dispatch'
        with:
          branch: gh-pages
          folder: ./document/doxygen
          commit-message: 'chore: deploy to gh-pages from @ ${{ github.repository }}@${{ github.sha }}'

  dynamic_analysis:
    name: Dynamic analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container: ryftchen/foo:latest

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./script/build.sh --release

      - name: Test
        run: |
          ./script/run.py --test --build rls

      - name: Run
        run: |
          ./script/run.py --check cov mem --build rls
...
