---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  precheck:
    name: Precheck
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 15

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2.13.0
        with:
          files: |
            **/*.{cpp,hpp,tpp,py,sh}
          incremental_files_only: false
          config: ./.github/actions/cspell/cspell.json
          verbose: true

  static_analysis:
    name: Static analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/build.sh --precheck --format --lint --count
          git status

      - name: Archive
        run: |
          ./script/build.sh --release --browser --doxygen

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: foo_artifact
          path: ./temporary/foo_*.tar.bz2
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.event_name == 'workflow_dispatch'
        with:
          branch: gh-pages
          folder: ./document/doxygen
          commit-message: 'chore: deploy to gh-pages from @ ${{ github.repository }}@${{ github.sha }}'

  dynamic_analysis:
    name: Dynamic analysis
    needs: precheck
    if: always() && ((needs.precheck.result == 'success') || (needs.precheck.result == 'skipped'))
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 15

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: |
          ./script/run.py --check cov mem --build dbg
          cat ./temporary/foo_run.report

      - name: Test
        run: |
          ./script/run.py --test --build rls
          cat ./temporary/foo_run.report

      - name: Run
        run: |
          ./script/run.py --build rls
          cat ./temporary/foo_run.report

  extended_analysis:
    name: Extended analysis
    needs: precheck
    if: always() && (needs.precheck.result == 'success')
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 15

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp
          config-file: ./.github/actions/codeql/codeql-config.yml

      - name: Manual build
        run: |
          ./script/build.sh
          ./script/build.sh --test

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
...
