---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Pre-check
        run: |
          ./script/build.sh --hook --spell --statistics
          git status

      - name: Static check
        run: |
          ./script/build.sh --format --lint
          git status

      - name: Create archive
        run: |
          ./script/build.sh --browser --doxygen

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: foo_artifact
          path: ./document/archive/foo_*.tar.bz2
          retention-days: 7

  dynamic_analysis:
    name: Dynamic analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Dynamic check
        run: |
          ./script/run.py --check cov mem --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Test debug version
        run: |
          ./script/run.py --test --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Test release version
        run: |
          ./script/run.py --test --build rls --repeat 1
          cat ./.cache/foo_run.report

      - name: Run debug version
        run: |
          ./script/run.py --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Run release version
        run: |
          ./script/run.py --build rls --repeat 1
          cat ./.cache/foo_run.report

  extended_analysis:
    name: Extended analysis
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: CodeQL init
        uses: github/codeql-action/init@v3.24.0
        with:
          languages: cpp
          config-file: ./.github/actions/codeql/codeql-config.yml

      - name: Manual build
        run: |
          ./script/build.sh
          ./script/build.sh --test

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v3.24.0

  deploy_pages:
    name: Deploy pages
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: 'pages'
      cancel-in-progress: false

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Documentation
        run: |
          ./script/build.sh --doxygen

      - name: Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

      - name: Configure pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: ./document/doxygen

      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
...
