---
name: Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      name:
        description: 'Pipeline'
        default: 'Manual trigger'
        required: false
  schedule:
    - cron: '0 0 * * MON'

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20
    permissions: write-all

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Static check
        run: |
          ./script/build.sh --hook --spell --format --lint --statistics
          git status
          ./script/build.sh --release --browser --doxygen

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: foo_artifact
          path: ./document/archive/foo_*.tar.bz2
          retention-days: 7

      - name: Initialize gh-pages branch
        if: github.event_name == 'push'
        run: |
          git remote update
          git fetch
          git checkout --track origin/gh-pages
          git reset --hard HEAD~1
          git push --force origin gh-pages
          git checkout master

      - name: Clean deployment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: github.event_name == 'push'
        with:
          branch: gh-pages
          folder: ./document/doxygen
          commit-message: 'chore: deploy to gh-pages from @ ${{ github.repository }}@${{ github.sha }}'

  dynamic_analysis:
    name: Dynamic analysis
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Dynamic check
        run: |
          ./script/run.py --check cov mem --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Test debug version
        run: |
          ./script/run.py --test --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Test release version
        run: |
          ./script/run.py --test --build rls --repeat 1
          cat ./.cache/foo_run.report

      - name: Run debug version
        run: |
          ./script/run.py --build dbg --repeat 1
          cat ./.cache/foo_run.report

      - name: Run release version
        run: |
          ./script/run.py --build rls --repeat 1
          cat ./.cache/foo_run.report

  extended_analysis:
    name: Extended analysis
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ryftchen/foo:latest
      options: --privileged
    timeout-minutes: 20

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Prepare
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.24.0
        with:
          languages: cpp
          config-file: ./.github/actions/codeql/codeql-config.yml

      - name: Manual build
        run: |
          ./script/build.sh
          ./script/build.sh --test

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3.24.0
...
